/** Mirrors navigator store category chips for CLIENT→PRO onboarding. */
export const STORE_CATEGORY_LABELS: Record<string, string> = {
  doors: "Двери",
  tiles: "Плитка",
  plumbing: "Сантехника",
  electrical: "Электротовары",
  flooring: "Напольные покрытия",
  paint: "Краска / ЛКМ",
  wallpaper: "Обои",
  lighting: "Освещение",
  furniture: "Мебель",
  kitchen: "Кухни",
  tools: "Инструменты",
  handles: "Фурнитура и замки",
  windows: "Окна",
  curtains: "Шторы",
  construction: "Стройматериалы",
  garden: "Сад и огород",
  heating: "Водоснабжение и отопление",
  bath_sauna: "Бани и сауны",
  pools: "Бассейны",
  textile: "Текстиль для дома",
  ceilings: "Потолки",
  decor: "Декор",
  gates: "Ворота",
  fireplaces: "Камины",
  smart_home: "Умный дом",
  climate: "Климат",
};

export const STORE_CATEGORY_CHIP_KEYS: string[] = [
  "doors",
  "tiles",
  "plumbing",
  "electrical",
  "flooring",
  "paint",
  "wallpaper",
  "lighting",
  "furniture",
  "kitchen",
  "tools",
  "handles",
  "windows",
  "curtains",
  "construction",
  "garden",
  "heating",
  "bath_sauna",
  "pools",
  "textile",
  "ceilings",
  "decor",
  "gates",
  "fireplaces",
  "smart_home",
  "climate",
];

export function storeCategoryChips(): { value: string; label: string }[] {
  return STORE_CATEGORY_CHIP_KEYS.map((value) => ({
    value,
    label: STORE_CATEGORY_LABELS[value] || value,
  }));
}
